apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nq8s83rko-nodejs
  janus-idp.io/tekton: nq8s83rko-nodejs
  backstage.io/kubernetes-id: nq8s83rko-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nq8s83rko-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
