apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nq8s83rko-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nq8s83rko-nodejs 
  name: nq8s83rko-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nq8s83rko-nodejs 
